### ISSUE TITLE
"SyntaxError: invalid syntax" for any dev-pipeline command

### ISSUE THREAD

**Issue by AnilShende** [dev-pipeline/dev-pipeline#17]
"SyntaxError: invalid syntax" for any dev-pipeline command.

### What you did ###
Successfully installed dev-pipeline.

### What you expected to have happen ###
Tried executing the command: **dev-pipeline configure -h**
Expecting some meaningful/appropriate guideline message if something is not correct.

### What actually happened ###

Below error appears for any _dev-pipeline_ command.

  **File "/usr/local/bin/dev-pipeline", line 7
    from devpipeline.exec.driver import main
                        ^
SyntaxError: invalid syntax**

**Comment by snewell** [comment]
Can you attach the contents of `/usr/local/bin/dev-pipeline`? That file is generated by `pip`/`setup.py`, and my line 7 doesn't look like yours.

**Comment by AnilShende** [comment]
Contents of '/usr/local/bin/dev-pipeline' for reference.
--------------------------------------------------------------------------------------

_#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from devpipeline.exec.driver import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())_
-------------------------------------------------------------------------------------------

**Comment by AnilShende** [comment]
Yes, I had used 'pip install' and it's version is **pip 9.0.1**.
Python version is '**Python 2.7.12**'. Do I need to  upgrade it to **3.x**? 

Also, can I copy your '/usr/local/bin/dev-pipeline' contents to mine directly? OR I need to reinstall dev-pipeline with Python 3.x again.

Thank you for your support.

**Comment by snewell** [comment]
Do you have anything like `pip3` installed? If so, try running `pip3 install` and see if that works. If you don't have `pip3`, try `python3 setup.py install`.

I thought that I had a note in the readme that dev-pipeline requires python3, but I can't find it now. Sorry about the confusion.

**Comment by AnilShende** [comment]
My apology for the delayed reply.

Yes, the command **python3 setup.py install .** worked as expected and am able to run the 'dev-pipeline' commands.

Appreciate your timely support.
Thank you.

**Comment by snewell** [comment]
Thanks for getting back, @AnilShende. Sorry again for the trouble.
